name: EnhancedPing
author: FoodCans
version: ${project.version}
api-version: 1.13
depend: [ ProtocolLib ]
main: dev.foodcans.enhancedping.EnhancedPing
commands:
  ping:
    description: View your ping
  pingtoggle:
    description: Toggle viewing the ping bar
  pingadmin:
    description: EnhancedPing administrative commands
